In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# эстетики ради
import seaborn as sns
sns.set()

In [2]:
country_data = pd.read_csv('../../data/raw/country_data.csv', parse_dates = ['report_dt'])

In [18]:
td = country_data.set_index('report_dt').sort_index().reset_index()

In [20]:
td.reset_index()

    index  report_dt       metric           val
0       0 2014-03-31  universalis  8.622745e+07
1       1 2014-04-30  universalis  8.416471e+07
2       2 2014-05-31  universalis  9.167135e+07
3       3 2014-06-30  universalis  9.340469e+07
4       4 2014-07-31  universalis  1.005175e+08
5       5 2014-08-31  universalis  1.037964e+08
6       6 2014-09-30  universalis  9.789162e+07
7       7 2014-10-31  universalis  1.056194e+08
8       8 2014-11-30  universalis  1.054549e+08
9       9 2014-12-31  universalis  1.289504e+08
10     10 2015-01-31  universalis  1.113378e+08
11     11 2015-02-28  universalis  1.074631e+08
12     12 2015-03-31  universalis  1.213251e+08
13     13 2015-04-30  universalis  1.214242e+08
14     14 2015-05-31  universalis  1.229587e+08
15     15 2015-06-30  universalis  1.314021e+08
16     16 2015-07-31  universalis  1.388567e+08
17     17 2015-08-31  universalis  1.405062e+08
18     18 2015-09-30  universalis  1.378141e+08
19     19 2015-10-31  universalis  1.473062e+08
20     20 2015-11-30  universalis  1.450877e+08
21     21 2015-12-31  universalis  1.724531e+08
22     22 2016-01-31  universalis  1.490172e+08
23     23 2016-02-28  universalis  1.421298e+08
24     24 2016-03-31  universalis  1.643927e+08
25     25 2016-04-30  universalis  1.633035e+08
26     26 2016-05-31  universalis  1.706107e+08
27     27 2016-06-30  universalis  1.744829e+08
28     28 2016-07-31  universalis  1.876438e+08
29     29 2016-08-31  universalis  1.874465e+08
30     30 2016-09-30  universalis  1.830529e+08
31     31 2016-10-31  universalis  1.972240e+08
32     32 2016-11-30  universalis  1.966519e+08
33     33 2016-12-31  universalis  2.326180e+08
34     34 2017-01-31  universalis  1.978598e+08
35     35 2017-02-28  universalis  1.871106e+08
36     36 2017-03-31  universalis  2.196657e+08
37     37 2017-04-30  universalis  2.186446e+08
38     38 2017-05-31  universalis  2.304417e+08
39     39 2017-06-30  universalis  2.345928e+08
40     40 2017-07-31  universalis  2.443310e+08
41     41 2017-08-31  universalis  2.480398e+08
42     42 2017-09-30  universalis  2.430839e+08
43     43 2017-10-31  universalis  2.557220e+08
44     44 2017-11-30  universalis  2.569599e+08
45     45 2017-12-31  universalis  3.009901e+08
46     46 2018-01-31  universalis  2.463728e+08
47     47 2018-02-28  universalis  2.381032e+08
48     48 2018-03-31  universalis  2.857078e+08
49     49 2018-04-30  universalis  2.761253e+08
50     50 2018-05-31  universalis  2.871304e+08
51     51 2018-06-30  universalis  2.976218e+08
52     52 2018-07-31  universalis  3.096799e+08
53     53 2018-08-31  universalis  3.136152e+08
54     54 2018-09-30  universalis  3.066953e+08
55     55 2018-10-31  universalis  3.139278e+08

In [12]:
from sklearn.linear_model import LinearRegression
LinearRegression()

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)